### ISSUE TITLE
Stop the lies

### ISSUE THREAD

**Issue by ghost** [ivanskodje-godotengine/godot-multiplayer-demo#1]
@ivanskodje   Ivan, you're not engineer. Stop falsely claiming to be an "Engineer". 
You know nothing about engineering. Engineering has nothing to do with sitting lazily behind a keyboard and writing code. Engineering is a real subject.  Engineering means designing and building real mechanical systems, like vehicular engines and turbojets. You software devs are claiming the most ridiculous of false claims these days. Software dev is easy and for kids, and has absolutely nothing to do with a real and serious complex subject like engineering. 

Stop the lies.  You will never be engineers.

**Comment by ducklin5** [comment]
lmao

**Comment by ivanskodje** [comment]
This is a good #1 issue, but I will have to mark this as a Unplanned feature ❤️
